/* Generated By:JJTree: Do not edit this line. ASTadd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTadd extends SimpleNode {
  public ASTadd(int id) {
    super(id);
  }

  public ASTadd(Prog2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85b26a17e98952053d9f19ef9862b329 (do not edit this line) */
