/* Generated By:JJTree: Do not edit this line. ASTappl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTappl extends SimpleNode {
  public ASTappl(int id) {
    super(id);
  }

  public ASTappl(Prog2 p, int id) {
    super(p, id);
  }
 public ASTappl clone(int id){
    return new ASTappl( id);
    }
}
/* JavaCC - OriginalChecksum=094bd6cb21ff46d92670ac10d81f7eaa (do not edit this line) */