/* Generated By:JJTree: Do not edit this line. ASTdiv.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdiv extends SimpleNode {
  public ASTdiv(int id) {
    super(id);
  }

  public ASTdiv(Prog2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b425dec34f055ca0fce8cf342d6d4af (do not edit this line) */
