/* Generated By:JJTree: Do not edit this line. ASTlamb.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlamb extends SimpleNode {
  public ASTlamb(int id) {
    super(id);
  }

  public ASTlamb(Prog2 p, int id) {
    super(p, id);
  }
public ASTlamb clone(int id){
    return new ASTlamb(id);
      }

}
/* JavaCC - OriginalChecksum=d3c68a313c9302592763eb829346b644 (do not edit this line) */