/* Generated By:JJTree: Do not edit this line. ASTmul.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmul extends SimpleNode {
  public ASTmul(int id) {
    super(id);
  }

  public ASTmul(Prog2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c002c224f9d6a6b4ec35b4f39106b617 (do not edit this line) */
