/* Generated By:JJTree: Do not edit this line. ASTMyID.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMyID extends SimpleNode {
private String name;

  public ASTMyID(int id) {
    super(id);
  }

  public ASTMyID(Prog2 p, int id) {
    super(p, id);
  }

public void setName(String n) {
    name = n;
  }

  public String toString() {
    return name;
  }
    public ASTMyID clone(int id){
	ASTMyID temp =new ASTMyID(id);
	temp.setName(name);
	return temp;
    }
}
/* JavaCC - OriginalChecksum=b04fb32a0f637bab7459f07cc93d8ce1 (do not edit this line) */