/* Generated By:JJTree: Do not edit this line. ASTsub.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsub extends SimpleNode {
  public ASTsub(int id) {
    super(id);
  }

  public ASTsub(Prog2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e2c13692faf14d424d72af6fbdcd34b3 (do not edit this line) */
