/* Generated By:JavaCC: Do not edit this line. Prog2TreeConstants.java Version 7.0.11 */
public interface Prog2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMUL = 4;
  public int JJTDIV = 5;
  public int JJTLAMB = 6;
  public int JJTAPPL = 7;
  public int JJTMYID = 8;
  public int JJTINTEGER = 9;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "add",
    "sub",
    "mul",
    "div",
    "lamb",
    "appl",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=badfe74fd60bca67aef6005356aeceec (do not edit this line) */
